# Generated by Django 3.1.2 on 2020-10-17 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmbalai', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fnf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmfnf', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Kodeoutput',
            fields=[
                ('kdoutput', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('nmkdoutput', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmks', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Paket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmpaket', models.CharField(max_length=250)),
                ('trgoutput', models.DecimalField(decimal_places=9, max_digits=15, null=True)),
                ('trgoutcome', models.DecimalField(decimal_places=9, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('balai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.balai')),
                ('fnf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.fnf')),
                ('kdoutput', models.ForeignKey(max_length=3, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.kodeoutput')),
                ('ks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.ks')),
            ],
        ),
        migrations.CreateModel(
            name='Satoutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmsatoutcome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Satoutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmsatoutput', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Sycmyc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmsycmyc', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Ta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wilayah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmwilayah', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Pagu',
            fields=[
                ('paket', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mildapp.paket')),
                ('pagurmp', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('phln', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('sbsn', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sistem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmsistem', models.CharField(max_length=250, null=True)),
                ('paket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.paket')),
            ],
        ),
        migrations.CreateModel(
            name='Satker',
            fields=[
                ('kdsatker', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('nmsatker', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('balai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.balai')),
                ('wilayah', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.wilayah')),
            ],
        ),
        migrations.CreateModel(
            name='Progres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keuangan', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('fisik', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('paket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.paket')),
            ],
        ),
        migrations.CreateModel(
            name='Ppk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmppk', models.CharField(max_length=100)),
                ('nmjabatan', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('email', models.CharField(max_length=255)),
                ('balai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.balai')),
                ('kdsatker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.satker')),
                ('wilayah', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.wilayah')),
            ],
        ),
        migrations.AddField(
            model_name='paket',
            name='ppk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.ppk'),
        ),
        migrations.AddField(
            model_name='paket',
            name='satker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.satker'),
        ),
        migrations.AddField(
            model_name='paket',
            name='satoutcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.satoutcome'),
        ),
        migrations.AddField(
            model_name='paket',
            name='satoutput',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.satoutput'),
        ),
        migrations.AddField(
            model_name='paket',
            name='sycmyc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.sycmyc'),
        ),
        migrations.AddField(
            model_name='paket',
            name='ta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.ta'),
        ),
        migrations.AddField(
            model_name='paket',
            name='tag',
            field=models.ManyToManyField(to='mildapp.Tag'),
        ),
        migrations.AddField(
            model_name='paket',
            name='wilayah',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.wilayah'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmnote', models.CharField(max_length=250, null=True)),
                ('lampirannote', models.CharField(max_length=250, null=True)),
                ('paket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.paket')),
            ],
        ),
        migrations.CreateModel(
            name='Lampiran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmlampiran', models.CharField(max_length=250, null=True)),
                ('lampiran', models.CharField(max_length=250, null=True)),
                ('paket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.paket')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmfoto', models.CharField(max_length=250, null=True)),
                ('foto', models.CharField(max_length=250, null=True)),
                ('paket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.paket')),
            ],
        ),
        migrations.AddField(
            model_name='balai',
            name='wilayah',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mildapp.wilayah'),
        ),
    ]
